"""empty message

Revision ID: da180fa2de9d
Revises: 99ff4ceae409
Create Date: 2023-05-19 23:12:14.395166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da180fa2de9d'
down_revision = '99ff4ceae409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_favorite_people_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_people')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_favorite_planets_fkey', type_='foreignkey')
        batch_op.drop_column('favorite_planets')

    with op.batch_alter_table('user_favs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('people_id')
        batch_op.drop_column('planets_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_favorite_planets_fkey', 'user_favs', ['favorite_planets'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_favorite_people_fkey', 'user_favs', ['favorite_people'], ['id'])

    # ### end Alembic commands ###
